# Tensorflow Version

## Hello World: Linear regression

In [1]:
import tensorflow
from tensorflow.keras import Sequential, layers
import numpy as np
print(tensorflow.__version__)

2.17.0


In [2]:
# Data that serves as input.

xs = np.array([-1, 0, 1, 2, 3, 4], dtype='float32')
ys = np.array([-3, -1, 1, 3, 5, 7], dtype='float32')

In [3]:
# Model creation and compilation.

model = Sequential([
                    layers.Dense(
                        input_shape=[1],  # Because we are going to take one xs value at a time in the NN.
                        units=1           # One neuron.
                    )
])

model.compile(
    loss='mse',
    optimizer='sgd',
    metrics=['accuracy']
)

/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [4]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense (Dense)                        │ (None, 1)                   │               2 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 2 (8.00 B)

 Trainable params: 2 (8.00 B)

 Non-trainable params: 0 (0.00 B)

In [5]:
# Fitting the training data in the model.

model.fit(
    xs,
    ys,
    epochs=500
)

Epoch 1/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 464ms/step - accuracy: 0.0000e+00 - loss: 53.4325
Epoch 2/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.0000e+00 - loss: 42.4451
Epoch 3/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 0.0000e+00 - loss: 33.7924
Epoch 4/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 0.0000e+00 - loss: 26.9767
Epoch 5/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.0000e+00 - loss: 21.6064
Epoch 6/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.0000e+00 - loss: 17.3735
Epoch 7/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.0000e+00 - loss: 14.0355
Epoch 8/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 0.1667 - loss: 11.4018
Epoch 9/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.1667 - loss: 9.3224
Epoch 10/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.1667 - loss: 7.6791
Epoch 11/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 0.1667 - loss: 6.3792
Epoch 12/500
1/1 ━━━━━━━━━━━━━━━━━━━━

In [6]:
# Prediction.

model.predict(np.array([10]))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step


array([[18.976095]], dtype=float32)

# Pytorch Version

## Hello World: Linear Regression

In [7]:
# Import Libraries

import torch

In [8]:
# Declare the single linear layer.

modelPytorch = torch.nn.Linear(
    in_features=1,
    out_features=1
    )

print(modelPytorch)

Linear(in_features=1, out_features=1, bias=True)


In [9]:
# Reshaping the tensors. Originally they were (1,6), this time is (6,1).
# What this does is give a full row at a time to the model.

xsTensor = torch.tensor(xs).reshape(-1,1)
ysTensor = torch.tensor(ys).reshape(-1,1)
print(xsTensor)


tensor([[-1.],
        [ 0.],
        [ 1.],
        [ 2.],
        [ 3.],
        [ 4.]])


In [10]:
# The initial weights and biases of the model.
for cell in modelPytorch.parameters():
  print(cell)

Parameter containing:
tensor([[-0.1813]], requires_grad=True)
Parameter containing:
tensor([0.0939], requires_grad=True)


In [14]:
# The loss and optimization parameters.

crit = torch.nn.MSELoss()
opti = torch.optim.SGD(modelPytorch.parameters(), lr=0.01)
print(opti.defaults)

{'lr': 0.01, 'momentum': 0, 'dampening': 0, 'weight_decay': 0, 'nesterov': False, 'maximize': False, 'foreach': None, 'differentiable': False, 'fused': None}


In [16]:
# A loop on a number of epochs.

for epoch in range(500):
    pred = modelPytorch(xsTensor)        # Extract predictions on the training data
    loss = crit(pred, ysTensor)          # Calculate the loss between the predicted and the original output.

    # Backpropagation
    opti.zero_grad()                     # Resets the gradients of all model parameters to zero.
    loss.backward()                      # The Pytorch automatic gradient function, to extract the loss' gradients.
    opti.step()                          # Function that updates the model's parameters based on the calculated gradients.

    print(f"Epoch {epoch}:--------->loss: {loss:>7f}")

0--------->loss: 18.622061
1--------->loss: 14.942035
2--------->loss: 12.040790
3--------->loss: 9.752374
4--------->loss: 7.946222
5--------->loss: 6.519609
6--------->loss: 5.391719
7--------->loss: 4.498958
8--------->loss: 3.791298
9--------->loss: 3.229374
10--------->loss: 2.782215
11--------->loss: 2.425452
12--------->loss: 2.139908
13--------->loss: 1.910498
14--------->loss: 1.725347
15--------->loss: 1.575115
16--------->loss: 1.452448
17--------->loss: 1.351559
18--------->loss: 1.267895
19--------->loss: 1.197871
20--------->loss: 1.138664
21--------->loss: 1.088052
22--------->loss: 1.044285
23--------->loss: 1.005984
24--------->loss: 0.972063
25--------->loss: 0.941666
26--------->loss: 0.914118
27--------->loss: 0.888885
28--------->loss: 0.865548
29--------->loss: 0.843772
30--------->loss: 0.823297
31--------->loss: 0.803912
32--------->loss: 0.785453
33--------->loss: 0.767789
34--------->loss: 0.750813
35--------->loss: 0.734443
36--------->loss: 0.718612
37------

In [17]:
# The resulting mode weights and biases.

for cell in modelPytorch.parameters():
  print(cell)

Parameter containing:
tensor([[1.9971]], requires_grad=True)
Parameter containing:
tensor([-0.9909], requires_grad=True)


In [20]:
# Test predicting a value not seen in the original training set.

modelPytorch(torch.tensor(10.).reshape(-1,1))

tensor([[18.9798]], grad_fn=<AddmmBackward0>)

# Observations

|Pytorch|Keras|
|-------|-----|
|More coding|Less coding|
|Gray box|Black box|
|Does not accepts Numpy arrays in model| Does accept Numpy arrays|
|Pythonic Loop|Built-in Loop|



